title: "Brandon Lewis - Senior Data Scientist Portfolio | DACH Region"
description: "Senior Data Scientist mit 6+ Jahren Erfahrung in ML-Engineering, Energiesystemen und Healthcare Analytics. Spezialisiert auf Zeitreihenprognosen und nachhaltige KI-Lösungen für den deutschen Markt."
url: "https://cyranothebard.github.io"
baseurl: ""

# SEO and Meta
keywords: "Data Scientist, Machine Learning Engineer, KI-Entwickler, Energiesysteme, Healthcare Analytics, Zeitreihenprognosen, DACH Region, Deutschland, Schweiz, Österreich"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

author: "Brandon Lewis"
twitter_username: ""
github_username: "cyranothebard"
linkedin_username: "brandon-lewis-data-science"
