title: "Brandon Lewis - Data Science Portfolio"
description: "Senior Data Scientist specializing in AI/ML for energy systems and healthcare analytics"
url: "https://cyranothebard.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

author: "Brandon Lewis"
twitter_username: ""
github_username: "cyranothebard"
linkedin_username: "brandon-lewis-data-science"
